"""Schema constants and version for BimodalHarness training data.

This module defines the canonical constants used across the schema package:
schema version, valid label values, valid formula tags (matching
DataExport.lean constructor names), valid GoalCategory values (matching
SuccessPatterns.lean GoalCategory constructors), and valid frame class names
(matching Axioms.lean FrameClass constructors).

Lean correspondence:
- VALID_FORMULA_TAGS: Formula inductive constructors in Bimodal.Syntax.Formula
- VALID_TOP_OPERATORS: GoalCategory constructors in Bimodal.Automation.SuccessPatterns
- VALID_FRAME_CLASSES: FrameClass constructors in Bimodal.ProofSystem.Axioms
"""

from __future__ import annotations

# Schema version — bump when the record schema changes in a backwards-incompatible way.
SCHEMA_VERSION = "1.0.0"

# Action space version — bump when axiom constructors are added/removed.
ACTION_SPACE_VERSION = "1.0.0"

# Valid label values for a TrainingRecord.
VALID_LABELS: frozenset[str] = frozenset({"valid", "invalid"})

# Valid difficulty tier strings.
VALID_DIFFICULTY_TIERS: frozenset[str] = frozenset(
    {
        "trivial",
        "easy",
        "medium",
        "hard",
        "very_hard",
    }
)

# Valid formula tag values matching DataExport.lean Formula.toJson.
# These are the 6 primitive Formula constructors.
VALID_FORMULA_TAGS: frozenset[str] = frozenset(
    {
        "atom",  # Formula.atom
        "bot",  # Formula.bot
        "imp",  # Formula.imp
        "box",  # Formula.box
        "untl",  # Formula.untl
        "snce",  # Formula.snce
    }
)

# Valid top-level operator category strings matching GoalCategory constructors
# in Bimodal.Automation.SuccessPatterns.  8 values.
VALID_TOP_OPERATORS: frozenset[str] = frozenset(
    {
        "Atom",  # GoalCategory.Atom
        "Bottom",  # GoalCategory.Bottom
        "Implication",  # GoalCategory.Implication
        "Box",  # GoalCategory.Box
        "AllPast",  # GoalCategory.AllPast  (Hφ -- all_past, a derived form)
        "AllFuture",  # GoalCategory.AllFuture (Gφ -- all_future, a derived form)
        "Until",  # GoalCategory.Until
        "Since",  # GoalCategory.Since
    }
)

# Valid frame class names matching FrameClass constructors.
VALID_FRAME_CLASSES: frozenset[str] = frozenset({"Base", "Dense", "Discrete"})

# Valid source identifiers for TrainingRecord.source.
VALID_SOURCES: frozenset[str] = frozenset(
    {
        "lean_export",  # Generated by BimodalLogic DataExport.lean
        "z3_generated",  # Generated by Z3 countermodel extraction
        "synthetic",  # Synthetically generated
        "unknown",  # Source unknown or mixed
    }
)
